#!/bin/bash

if [[ "$SHELL" == "/bin/zsh" ]] ; then
  ln -fs ~/.dotfiles/profile ~/.zprofile
  ln -fs ~/.dotfiles/zshrc ~/.zshrc
else
  ln -fs ~/.dotfiles/bash_login ~/.bash_login
  ln -fs ~/.dotfiles/iterm2_shell_integration.bash ~/.iterm2_shell_integration.bash
  ln -fs ~/.dotfiles/profile ~/.profile
fi

ln -fs ~/.dotfiles/ackrc ~/.ackrc
ln -fs ~/.dotfiles/aliases ~/.aliases
ln -fs ~/.dotfiles/editrc ~/.editrc
ln -fs ~/.dotfiles/git-completion.bash ~/.git-completion.bash
ln -fs ~/.dotfiles/gitignore_global ~/.gitignore_global
ln -fs ~/.dotfiles/irbrc ~/.irbrc
ln -fs ~/.dotfiles/pryrc ~/.pryrc
ln -fs ~/.dotfiles/railsrc ~/.railsrc
ln -fs ~/.dotfiles/rdebugrc ~/.rdebugrc
ln -fs ~/.dotfiles/tmux.conf ~/.tmux.conf
ln -fs ~/.dotfiles/tmuxinator ~/.tmuxinator
./gitconfig

if [[ "$TERM_PROGRAM" == "iTerm.app" ]] ; then
  echo "You appear to be running this script from within iTerm.app which could"
  echo "overwrite your new preferences on quit."
  echo "Please quit iTerm and run this from Terminal.app or an SSH session."
  exit 3
fi

if ps wwwaux | egrep -q 'iTerm\.app' >/dev/null ; then
  echo "You appear to have iTerm.app currently running. Please quit the"
  echo "application so your updates won't get overridden on quit."
  exit 4
fi
